apiVersion: v1
kind: Pod
metadata:
  name: docker-playground
  labels:
    app: docker-lab
spec:
  containers:
    - name: docker-client
      image: ubuntu:24.04
      command:
        - /bin/bash
        - -c
        - apt-get update && apt-get install -y curl ca-certificates iptables && curl -fsSL https://get.docker.com | sh && (dockerd > /var/log/dockerd.log 2>&1 &) && sleep infinity
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false
      stdin: true
      tty: true
