apiVersion: v1
kind: Pod
metadata:
  name: lab-user123
  labels:
    app: byolabs
    user: user123
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      ports:
        - containerPort: 22
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
